"""Parse all HTML reports and generate SUMMARY.md."""

import html as html_mod
import re
from pathlib import Path

reports_dir = Path("reports")
rows = []

for f in sorted(reports_dir.glob("*.html")):
    text = f.read_text(encoding="utf-8")

    m = re.search(r"<h1>(.*?)</h1>", text)
    title = html_mod.unescape(m.group(1)).strip() if m else f.stem

    metrics = {}
    for card in re.finditer(
        r'<div class="metric-card">\s*<div class="label">(.*?)</div>\s*'
        r'<div class="value[^"]*">(.*?)</div>',
        text,
    ):
        label = card.group(1).strip()
        value = card.group(2).strip()
        metrics[label] = value

    rows.append({
        "file": f.name,
        "title": title,
        "total_return": metrics.get("Total Return", ""),
        "win_rate": metrics.get("Win Rate", ""),
        "avg_win": metrics.get("Avg Win", ""),
        "avg_loss": metrics.get("Avg Loss", ""),
        "total_trades": metrics.get("Total Trades", ""),
        "bh_return": metrics.get("B&H Return", ""),
        "alpha": metrics.get("Alpha vs B&H", ""),
        "sharpe": metrics.get("Sharpe Ratio", ""),
        "profit_factor": metrics.get("Profit Factor", ""),
    })

lines = []
lines.append("# Backtest Summary\n")
lines.append(
    "| # | Report | Strategy | Total Return | B&H | Alpha | "
    "Trades | Win Rate | Avg Win | Avg Loss | Sharpe | PF |"
)
lines.append(
    "|---|--------|----------|-------------|-----|-------|"
    "--------|----------|---------|----------|--------|-----|"
)

for i, r in enumerate(rows, 1):
    lines.append(
        f"| {i} "
        f"| [{r['file']}](reports/{r['file']}) "
        f"| {r['title']} "
        f"| {r['total_return']} "
        f"| {r['bh_return']} "
        f"| {r['alpha']} "
        f"| {r['total_trades']} "
        f"| {r['win_rate']} "
        f"| {r['avg_win']} "
        f"| {r['avg_loss']} "
        f"| {r['sharpe']} "
        f"| {r['profit_factor']} |"
    )

lines.append("")
lines.append("---")
lines.append("*Generated by Python Backtester*")
lines.append("")

Path("SUMMARY.md").write_text("\n".join(lines), encoding="utf-8")
print(f"Summary written with {len(rows)} reports")
